stages:
    - build
    - cleanup_build

before_script:
    - "if not exist R:\ (net use R: \\\\nncv03a-cifs.inn.intel.com\\rdrive\\wref1)"
    - set HOME=C:\Users\nstester
    - set ALLOY_GIT=1
    - set ICS_WSROOT=%HOME%\alloy_workspaces
    - set WS_NAME=xmain1
    - set CURRENT_RUN_RESULTS=%ICS_WSROOT%\%WS_NAME%\alloy\results
    
build_job:
    stage: build
    script:
        - "if exist %CURRENT_RUN_RESULTS% (rmdir %CURRENT_RUN_RESULTS% /S /Q)"
        - call R:\u4win\setenv.bat
        - call R:\ics\itools\win\bin\icssetup.bat
        - call cd %ICS_WSROOT%
        - call ics set ws %WS_NAME%
        - call ics update head
        - alloy run -file xmain_pgopti
    only:
        - xmain
        
cleanup_job:
    stage: cleanup_build
    script:
    - "if exist %CURRENT_RUN_RESULTS%\\alloy.log (copy %CURRENT_RUN_RESULTS%\\alloy.log)"
    - "if exist %CURRENT_RUN_RESULTS%\\problem.log (copy %CURRENT_RUN_RESULTS%\\problem.log)"
    - "if exist %CURRENT_RUN_RESULTS%\\status.log (copy %CURRENT_RUN_RESULTS%\\status.log)"
    - "if exist %CURRENT_RUN_RESULTS%\\copy.log (copy %CURRENT_RUN_RESULTS%\\copy.log)"
    - "if exist %CURRENT_RUN_RESULTS%\\warning.log (copy %CURRENT_RUN_RESULTS%\\warning.log)"
    - "if exist %CURRENT_RUN_RESULTS%\\fail.log (copy %CURRENT_RUN_RESULTS%\\fail.log)"
    - "if exist %CURRENT_RUN_RESULTS% (rmdir %CURRENT_RUN_RESULTS% /S /Q)"
    artifacts:
        paths:
        - alloy.log
        - problem.log
        - status.log
        - copy.log
        - warning.log
        - fail.log
    only:
        - xmain
    when: always

